name: Deploy to demo.abris.site

on:
  push:
    branches: [ master ]

env:
  DEPLOY_PATH: /home/github-deploy-components/prod_www
  BUILD_SCRIPT_OUTPUT: site

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm run doc:gen
      - run: sed  -i "/head/r site/ga4.txt" site/index.html
      - run: rm -rf site/ga4.txt
      
      - name: copy files via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_ABRIS_HOST }}
          port: ${{ secrets.DEPLOY_ABRIS_PORT }}
          username: ${{ secrets.DEPLOY_ABRIS_USERNAME }}
          key: ${{ secrets.DEPLOY_ABRIS_KEY }}
          source: "${{ env.BUILD_SCRIPT_OUTPUT }}/*"
          target: ${{ env.DEPLOY_PATH }}
          strip_components: 1
      - name: Print Info
        run: echo "Deployed at https://abris.site/"
